-- MySQL Script generated by MySQL Workbench
-- lun. 09 mars 2026 10:56:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e22206673_db1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e22206673_db1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e22206673_db1` DEFAULT CHARACTER SET utf8 ;
USE `e22206673_db1` ;

-- -----------------------------------------------------
-- Table `e22206673_db1`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22206673_db1`.`User` (
  `user_id` CHAR(36) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `is_admin` BOOLEAN NOT NULL,
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22206673_db1`.`Board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22206673_db1`.`Board` (
  `board_id` CHAR(36) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`board_id`),
  UNIQUE INDEX `table_id_UNIQUE` (`board_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22206673_db1`.`KanbanColumn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22206673_db1`.`KanbanColumn` (
  `kanban_column_id` CHAR(36) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `position` INT NOT NULL,
  `board_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`kanban_column_id`, `board_id`),
  UNIQUE INDEX `column_id_UNIQUE` (`kanban_column_id` ASC) VISIBLE,
  INDEX `fk_KanbanColumn_Board1_idx` (`board_id` ASC) VISIBLE,
  CONSTRAINT `fk_KanbanColumn_Board1`
    FOREIGN KEY (`board_id`)
    REFERENCES `e22206673_db1`.`Board` (`board_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22206673_db1`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22206673_db1`.`Task` (
  `task_id` CHAR(36) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `deadline` DATE NULL,
  `priority` ENUM("Strong", "Medium", "Low") NULL,
  `user_id` CHAR(36) NULL,
  `kanban_column_id` CHAR(36) NOT NULL,
  `position` INT NULL,
  PRIMARY KEY (`task_id`, `user_id`, `kanban_column_id`),
  UNIQUE INDEX `task_id_UNIQUE` (`task_id` ASC) VISIBLE,
  INDEX `fk_Task_User1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Task_KanbanColumn1_idx` (`kanban_column_id` ASC) VISIBLE,
  CONSTRAINT `fk_Task_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `e22206673_db1`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Task_KanbanColumn1`
    FOREIGN KEY (`kanban_column_id`)
    REFERENCES `e22206673_db1`.`KanbanColumn` (`kanban_column_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22206673_db1`.`BoardMember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22206673_db1`.`BoardMember` (
  `user_id` CHAR(36) NOT NULL,
  `board_id` CHAR(36) NOT NULL,
  `role` ENUM("Member", "Owner", "Invited") DEFAULT 'Invited',
  PRIMARY KEY (`user_id`, `board_id`),
  INDEX `fk_BoardMember_Board1_idx` (`board_id` ASC) VISIBLE,
  CONSTRAINT `fk_BoardMember_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `e22206673_db1`.`User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_BoardMember_Board1`
    FOREIGN KEY (`board_id`)
    REFERENCES `e22206673_db1`.`Board` (`board_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

