-- MySQL Script generated by MySQL Workbench
-- lun. 09 mars 2026 10:56:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(10) NOT NULL,
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Board` (
  `board_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`board_id`),
  UNIQUE INDEX `table_id_UNIQUE` (`board_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KanbanColumn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KanbanColumn` (
  `kanban_column_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `position` INT NOT NULL,
  `board_id` INT NOT NULL,
  PRIMARY KEY (`kanban_column_id`, `board_id`),
  UNIQUE INDEX `column_id_UNIQUE` (`kanban_column_id` ASC) VISIBLE,
  INDEX `fk_KanbanColumn_Board1_idx` (`board_id` ASC) VISIBLE,
  CONSTRAINT `fk_KanbanColumn_Board1`
    FOREIGN KEY (`board_id`)
    REFERENCES `mydb`.`Board` (`board_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `deadline` DATE NULL,
  `priority` ENUM("Strong", "Medium", "Low") NULL,
  `user_id` INT NOT NULL,
  `kanban_column_id` INT NOT NULL,
  `position` INT NULL,
  PRIMARY KEY (`task_id`, `user_id`, `kanban_column_id`),
  UNIQUE INDEX `task_id_UNIQUE` (`task_id` ASC) VISIBLE,
  INDEX `fk_Task_User1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Task_KanbanColumn1_idx` (`kanban_column_id` ASC) VISIBLE,
  CONSTRAINT `fk_Task_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_KanbanColumn1`
    FOREIGN KEY (`kanban_column_id`)
    REFERENCES `mydb`.`KanbanColumn` (`kanban_column_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BoardMember`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BoardMember` (
  `user_id` INT NOT NULL,
  `board_id` INT NOT NULL,
  `role` ENUM("Member", "Owner", "Invited") NULL,
  PRIMARY KEY (`user_id`, `board_id`),
  INDEX `fk_BoardMember_Board1_idx` (`board_id` ASC) VISIBLE,
  CONSTRAINT `fk_BoardMember_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BoardMember_Board1`
    FOREIGN KEY (`board_id`)
    REFERENCES `mydb`.`Board` (`board_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Invitation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Invitation` (
  `invitation_id` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM("Pending", "Accepted", "Rejected") NULL,
  `inviter_id` INT NOT NULL,
  `board_id` INT NOT NULL,
  PRIMARY KEY (`invitation_id`, `inviter_id`, `board_id`),
  UNIQUE INDEX `invitation_id_UNIQUE` (`invitation_id` ASC) VISIBLE,
  INDEX `fk_Invitation_Board1_idx` (`board_id` ASC) VISIBLE,
  INDEX `fk_Invitation_User1_idx` (`inviter_id` ASC) VISIBLE,
  CONSTRAINT `fk_Invitation_Board1`
    FOREIGN KEY (`board_id`)
    REFERENCES `mydb`.`Board` (`board_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invitation_User1`
    FOREIGN KEY (`inviter_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

