server.port=8080

spring.datasource.url=jdbc:mariadb://obiwan.univ-brest.fr:3306/e22206673_db1
spring.datasource.username=e22206673sql
spring.datasource.password=rDoKnVI6
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuration pour MongoDB
#spring.data.mongodb.uri=mongodb://localhost:27017/votre_base_mongo